-- 绑定变量（会话级别）
-- VARIABLE bv VARCHAR2(30)
-- BEGIN
-- 	:bv := 'SAN';
-- END;
-- /
-- DECLARE
-- 	LV_WHOM VARCHAR2(30);
-- BEGIN
-- 	LV_WHOM := :bv;
--   DBMS_OUTPUT.PUT_LINE('Hello '|| LV_WHOM ||'.');
-- END;
-- /
-- 创建存储过程
-- CREATE OR REPLACE PROCEDURE HELLO_PROCEDURE
-- (PV_WHOM VARCHAR2 ) IS
-- BEGIN
--   DBMS_OUTPUT.PUT_LINE('Hello '||PV_WHOM||'.');
-- END;
-- /
-- 创建函数
-- CREATE OR REPLACE FUNCTION HELLO_FUNCTION
-- (PV_WHOM VARCHAR2 ) RETURN VARCHAR2 IS
-- BEGIN
--   RETURN '你好 '||PV_WHOM||'.';
-- END;
DECLARE
	FUNCTION B RETURN VARCHAR2 IS
	BEGIN
		RETURN 'HELLO';
	END B;
	PROCEDURE A IS
	BEGIN
		DBMS_OUTPUT.PUT_LINE(B||' WORLD!');
	END A;
BEGIN
	A;
END;
/